### ISSUE TITLE
intro

### ISSUE THREAD

**Issue by jovo** [neurodata/extensible-science-paper#10]
literally enumerate the challenges in par 2.
first,
second, 
third, 
etc.

you write "first", but then no "second".

in par 3, build up the solution:
data standards solve some stuff
jupyter solves some stuff
containers solve some stuff
science in the cloud solves all stuff

paragraph 3 is where you get to put our work in the context of previous art, explicitly.

**Comment by gkiar** [comment]
I think I've solved. Check back?
