### ISSUE TITLE
figs feedback

### ISSUE THREAD

**Issue by jovo** [neurodata/extensible-science-paper#17]
fantastic draft.

fig 1: looks great

table 1: i'd left align everything. i don't agree with all the pro's and cons, let's discuss

fig 2:  can't read things, and figure shown is a bit redundant.  i presume the caption is just a stand in. let's brainstorm a bit about how to make it more clear, zooming in on crucial bits, for example.

fig 3: i think it should be fig 3 and 4 (separately).  i never like (a) and (b) the way latex does it.  i think axes should typically be log X, rather than X, so you don't need to write 10^n all the time.  nnz one isn't very clear, i'd use violin plot.  though color is gratuitous here, might be worth it?

let's discuss more tomorrow

**Comment by gkiar** [comment]
good chat, working on updates now :)
