### ISSUE TITLE
in methods section

### ISSUE THREAD

**Issue by jovo** [neurodata/extensible-science-paper#19]
for each decision, put a paragraph per decision, including why we made the decision, 
and the details of what it means to have made that decision.

eg, for S3, what commands do we use?
for BIDS, did we need to organize derivatives, subject level/group level, somehow to stay in accordance with them.

jupyter vs. Rnotebooks (which now exist), we don't need a good reason, we can say other options would also be great.

etc.

**Comment by gkiar** [comment]
I think I've done this, though in sentences at the end of existing paragraphs rather than full separate paragraphs. At least closing for now as an iteration and can revisit later :)
