### ISSUE TITLE
results section

### ISSUE THREAD

**Issue by jovo** [neurodata/extensible-science-paper#20]
should have the following subsections:
1. intro paragraphs
2. subject level analysis - _briefly_ describe each step, i think this has to include computing subject level graph stats.  reference future manuscript.
3. population level analysis - _briefly_ describe each step, also reference future manuscript. i think this is just plotting them all together?
4. extension options - describe the kinds of extensions, refer to figure.
5. demo - explain what the demo does

i've added blank sections for you :)

**Comment by gkiar** [comment]
I think done!
