### ISSUE TITLE
feedback edit

### ISSUE THREAD

**Issue by jovo** [neurodata/extensible-science-paper#48]
i made some comments, and i sent to brett's person for more detailed minor edits.
in general, it is great.

our plan, iirc, is to submit *post* cluster deployment in the cloud, right?
i've now lost track of where we are documenting this plan?
does not seem to be github, it is asana?
please link to it in the comment, and then close this issue when you address my minor comments 

i did a 

```
% @gkiar <blah>
````

for my comments in the text

**Comment by gkiar** [comment]
Thanks! I'll get to these this week. & yes, that is the plan, though I believe it is not documented anywhere (except now). I'll fix that

**Comment by gkiar** [comment]
Responded to all comments in the document & updated accordingly based upon our ECS deployment. One open question for you @jovo before I'm ready to submit: The paragraph near the end of the discussion about the workshops/conferences that spawned this idea feels out of place. I don't know how you feel about scrapping it, but I think that might make me happy. Eager to hear your thoughts. 😄

**Comment by gkiar** [comment]
You responded in slack - closing! :)
