### ISSUE TITLE
paragraph 2 of paper

### ISSUE THREAD

**Issue by jovo** [neurodata/extensible-science-paper#7]
there are several challenges, para 2 should enumerate them each in a sentence:
- [x] data not open access
- [x] data not organized in a fashion immediately amenable to analysis
- [x] code not open source
- [x] code not organized in a fashion immediately amenable to run
- [x] various software dependencies/installations (of particular versions)
- [x] various hardware dependencies

paragraph 3 provides conceptual explaination of our resolution of all of these.

makes sense?

**Comment by gkiar** [comment]
Yup! done in most recent version on overleaf.
